/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CharacterId = IDL.Nat;
export const Trait = IDL.Record({
  'source' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'characterId' : CharacterId,
});
export const CustomClass = IDL.Record({
  'features' : IDL.Vec(Trait),
  'name' : IDL.Text,
  'hitDie' : IDL.Nat,
  'description' : IDL.Text,
  'proficiencies' : IDL.Vec(IDL.Text),
});
export const ClassId = IDL.Nat;
export const InventoryItem = IDL.Record({
  'weight' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'equipped' : IDL.Bool,
  'quantity' : IDL.Nat,
  'characterId' : CharacterId,
});
export const InventoryItemId = IDL.Nat;
export const Abilities = IDL.Record({
  'cha' : IDL.Nat,
  'con' : IDL.Nat,
  'dex' : IDL.Nat,
  'int' : IDL.Nat,
  'str' : IDL.Nat,
  'wis' : IDL.Nat,
});
export const CustomRace = IDL.Record({
  'abilityBonuses' : Abilities,
  'traits' : IDL.Vec(Trait),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'speed' : IDL.Nat,
});
export const RaceId = IDL.Nat;
export const Spell = IDL.Record({
  'duration' : IDL.Text,
  'school' : IDL.Text,
  'name' : IDL.Text,
  'damageEffect' : IDL.Text,
  'components' : IDL.Text,
  'description' : IDL.Text,
  'level' : IDL.Nat,
  'characterId' : CharacterId,
  'range' : IDL.Text,
  'castingTime' : IDL.Text,
});
export const SpellId = IDL.Nat;
export const TraitId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Skills = IDL.Record({
  'perception' : IDL.Bool,
  'animalHandling' : IDL.Bool,
  'nature' : IDL.Bool,
  'investigation' : IDL.Bool,
  'deception' : IDL.Bool,
  'sleightOfHand' : IDL.Bool,
  'acrobatics' : IDL.Bool,
  'athletics' : IDL.Bool,
  'history' : IDL.Bool,
  'persuasion' : IDL.Bool,
  'medicine' : IDL.Bool,
  'stealth' : IDL.Bool,
  'survival' : IDL.Bool,
  'insight' : IDL.Bool,
  'intimidation' : IDL.Bool,
  'performance' : IDL.Bool,
  'arcana' : IDL.Bool,
  'religion' : IDL.Bool,
});
export const Character = IDL.Record({
  'ac' : IDL.Nat,
  'cha' : IDL.Nat,
  'con' : IDL.Nat,
  'dex' : IDL.Nat,
  'int' : IDL.Nat,
  'str' : IDL.Nat,
  'wis' : IDL.Nat,
  'spellSlots' : IDL.Vec(IDL.Nat),
  'characterClass' : IDL.Text,
  'background' : IDL.Text,
  'hpMax' : IDL.Nat,
  'owner' : IDL.Principal,
  'gold' : IDL.Nat,
  'name' : IDL.Text,
  'race' : IDL.Text,
  'hpCurrent' : IDL.Nat,
  'level' : IDL.Nat,
  'speed' : IDL.Nat,
  'gender' : IDL.Text,
  'notes' : IDL.Text,
  'skills' : Skills,
  'proficiencyBonus' : IDL.Nat,
  'alignment' : IDL.Text,
  'initiative' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Settings = IDL.Record({ 'maxLevel' : IDL.Nat });
export const CustomSpellId = IDL.Nat;
export const CustomSpell = IDL.Record({
  'name' : IDL.Text,
  'level' : IDL.Nat,
  'school' : IDL.Text,
  'castingTime' : IDL.Text,
  'range' : IDL.Text,
  'components' : IDL.Text,
  'duration' : IDL.Text,
  'damageEffect' : IDL.Text,
  'description' : IDL.Text,
  'owner' : IDL.Principal,
});
export const CustomItemId = IDL.Nat;
export const CustomItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'weight' : IDL.Text,
  'value' : IDL.Text,
  'itemType' : IDL.Text,
  'rarity' : IDL.Text,
  'owner' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClass' : IDL.Func([CustomClass], [ClassId], []),
  'addItem' : IDL.Func([InventoryItem], [InventoryItemId], []),
  'addRace' : IDL.Func([CustomRace], [RaceId], []),
  'addSpell' : IDL.Func([Spell], [SpellId], []),
  'addTrait' : IDL.Func([Trait], [TraitId], []),
  'addCustomSpell' : IDL.Func([CustomSpell], [CustomSpellId], []),
  'addCustomItem' : IDL.Func([CustomItem], [CustomItemId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCharacter' : IDL.Func([Character], [CharacterId], []),
  'deleteCharacter' : IDL.Func([CharacterId], [], []),
  'deleteClass' : IDL.Func([ClassId], [], []),
  'deleteItem' : IDL.Func([InventoryItemId], [], []),
  'deleteRace' : IDL.Func([RaceId], [], []),
  'deleteSpell' : IDL.Func([SpellId], [], []),
  'deleteTrait' : IDL.Func([TraitId], [], []),
  'deleteCustomSpell' : IDL.Func([CustomSpellId], [], []),
  'deleteCustomItem' : IDL.Func([CustomItemId], [], []),
  'getAllCharacters' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(CharacterId, Character))],
      ['query'],
    ),
  'getAllClasses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ClassId, CustomClass))],
      ['query'],
    ),
  'getAllRaces' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(RaceId, CustomRace))],
      ['query'],
    ),
  'getAllCustomSpells' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(CustomSpellId, CustomSpell))],
      ['query'],
    ),
  'getAllCustomItems' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(CustomItemId, CustomItem))],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacter' : IDL.Func([CharacterId], [IDL.Opt(Character)], ['query']),
  'getItemsByCharacter' : IDL.Func(
      [CharacterId],
      [IDL.Vec(IDL.Tuple(InventoryItemId, InventoryItem))],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getSpellsByCharacter' : IDL.Func(
      [CharacterId],
      [IDL.Vec(IDL.Tuple(SpellId, Spell))],
      ['query'],
    ),
  'getTraitsByCharacter' : IDL.Func(
      [CharacterId],
      [IDL.Vec(IDL.Tuple(TraitId, Trait))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCharacter' : IDL.Func([CharacterId, Character], [], []),
  'updateClass' : IDL.Func([ClassId, CustomClass], [], []),
  'updateItem' : IDL.Func([InventoryItemId, InventoryItem], [], []),
  'updateRace' : IDL.Func([RaceId, CustomRace], [], []),
  'updateSettings' : IDL.Func([Settings], [], []),
  'updateSpell' : IDL.Func([SpellId, Spell], [], []),
  'updateTrait' : IDL.Func([TraitId, Trait], [], []),
  'updateCustomSpell' : IDL.Func([CustomSpellId, CustomSpell], [], []),
  'updateCustomItem' : IDL.Func([CustomItemId, CustomItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CharacterId = IDL.Nat;
  const Trait = IDL.Record({
    'source' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'characterId' : CharacterId,
  });
  const CustomClass = IDL.Record({
    'features' : IDL.Vec(Trait),
    'name' : IDL.Text,
    'hitDie' : IDL.Nat,
    'description' : IDL.Text,
    'proficiencies' : IDL.Vec(IDL.Text),
  });
  const ClassId = IDL.Nat;
  const InventoryItem = IDL.Record({
    'weight' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'equipped' : IDL.Bool,
    'quantity' : IDL.Nat,
    'characterId' : CharacterId,
  });
  const InventoryItemId = IDL.Nat;
  const Abilities = IDL.Record({
    'cha' : IDL.Nat,
    'con' : IDL.Nat,
    'dex' : IDL.Nat,
    'int' : IDL.Nat,
    'str' : IDL.Nat,
    'wis' : IDL.Nat,
  });
  const CustomRace = IDL.Record({
    'abilityBonuses' : Abilities,
    'traits' : IDL.Vec(Trait),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'speed' : IDL.Nat,
  });
  const RaceId = IDL.Nat;
  const Spell = IDL.Record({
    'duration' : IDL.Text,
    'school' : IDL.Text,
    'name' : IDL.Text,
    'damageEffect' : IDL.Text,
    'components' : IDL.Text,
    'description' : IDL.Text,
    'level' : IDL.Nat,
    'characterId' : CharacterId,
    'range' : IDL.Text,
    'castingTime' : IDL.Text,
  });
  const SpellId = IDL.Nat;
  const TraitId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Skills = IDL.Record({
    'perception' : IDL.Bool,
    'animalHandling' : IDL.Bool,
    'nature' : IDL.Bool,
    'investigation' : IDL.Bool,
    'deception' : IDL.Bool,
    'sleightOfHand' : IDL.Bool,
    'acrobatics' : IDL.Bool,
    'athletics' : IDL.Bool,
    'history' : IDL.Bool,
    'persuasion' : IDL.Bool,
    'medicine' : IDL.Bool,
    'stealth' : IDL.Bool,
    'survival' : IDL.Bool,
    'insight' : IDL.Bool,
    'intimidation' : IDL.Bool,
    'performance' : IDL.Bool,
    'arcana' : IDL.Bool,
    'religion' : IDL.Bool,
  });
  const Character = IDL.Record({
    'ac' : IDL.Nat,
    'cha' : IDL.Nat,
    'con' : IDL.Nat,
    'dex' : IDL.Nat,
    'int' : IDL.Nat,
    'str' : IDL.Nat,
    'wis' : IDL.Nat,
    'spellSlots' : IDL.Vec(IDL.Nat),
    'characterClass' : IDL.Text,
    'background' : IDL.Text,
    'hpMax' : IDL.Nat,
    'owner' : IDL.Principal,
    'gold' : IDL.Nat,
    'name' : IDL.Text,
    'race' : IDL.Text,
    'hpCurrent' : IDL.Nat,
    'level' : IDL.Nat,
    'speed' : IDL.Nat,
    'gender' : IDL.Text,
    'notes' : IDL.Text,
    'skills' : Skills,
    'proficiencyBonus' : IDL.Nat,
    'alignment' : IDL.Text,
    'initiative' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Settings = IDL.Record({ 'maxLevel' : IDL.Nat });
  const CustomSpellId = IDL.Nat;
  const CustomSpell = IDL.Record({
    'name' : IDL.Text,
    'level' : IDL.Nat,
    'school' : IDL.Text,
    'castingTime' : IDL.Text,
    'range' : IDL.Text,
    'components' : IDL.Text,
    'duration' : IDL.Text,
    'damageEffect' : IDL.Text,
    'description' : IDL.Text,
    'owner' : IDL.Principal,
  });
  const CustomItemId = IDL.Nat;
  const CustomItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'weight' : IDL.Text,
    'value' : IDL.Text,
    'itemType' : IDL.Text,
    'rarity' : IDL.Text,
    'owner' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClass' : IDL.Func([CustomClass], [ClassId], []),
    'addItem' : IDL.Func([InventoryItem], [InventoryItemId], []),
    'addRace' : IDL.Func([CustomRace], [RaceId], []),
    'addSpell' : IDL.Func([Spell], [SpellId], []),
    'addTrait' : IDL.Func([Trait], [TraitId], []),
    'addCustomSpell' : IDL.Func([CustomSpell], [CustomSpellId], []),
    'addCustomItem' : IDL.Func([CustomItem], [CustomItemId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCharacter' : IDL.Func([Character], [CharacterId], []),
    'deleteCharacter' : IDL.Func([CharacterId], [], []),
    'deleteClass' : IDL.Func([ClassId], [], []),
    'deleteItem' : IDL.Func([InventoryItemId], [], []),
    'deleteRace' : IDL.Func([RaceId], [], []),
    'deleteSpell' : IDL.Func([SpellId], [], []),
    'deleteTrait' : IDL.Func([TraitId], [], []),
    'deleteCustomSpell' : IDL.Func([CustomSpellId], [], []),
    'deleteCustomItem' : IDL.Func([CustomItemId], [], []),
    'getAllCharacters' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(CharacterId, Character))],
        ['query'],
      ),
    'getAllClasses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ClassId, CustomClass))],
        ['query'],
      ),
    'getAllRaces' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(RaceId, CustomRace))],
        ['query'],
      ),
    'getAllCustomSpells' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(CustomSpellId, CustomSpell))],
        ['query'],
      ),
    'getAllCustomItems' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(CustomItemId, CustomItem))],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacter' : IDL.Func([CharacterId], [IDL.Opt(Character)], ['query']),
    'getItemsByCharacter' : IDL.Func(
        [CharacterId],
        [IDL.Vec(IDL.Tuple(InventoryItemId, InventoryItem))],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getSpellsByCharacter' : IDL.Func(
        [CharacterId],
        [IDL.Vec(IDL.Tuple(SpellId, Spell))],
        ['query'],
      ),
    'getTraitsByCharacter' : IDL.Func(
        [CharacterId],
        [IDL.Vec(IDL.Tuple(TraitId, Trait))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCharacter' : IDL.Func([CharacterId, Character], [], []),
    'updateClass' : IDL.Func([ClassId, CustomClass], [], []),
    'updateItem' : IDL.Func([InventoryItemId, InventoryItem], [], []),
    'updateRace' : IDL.Func([RaceId, CustomRace], [], []),
    'updateSettings' : IDL.Func([Settings], [], []),
    'updateSpell' : IDL.Func([SpellId, Spell], [], []),
    'updateTrait' : IDL.Func([TraitId, Trait], [], []),
    'updateCustomSpell' : IDL.Func([CustomSpellId, CustomSpell], [], []),
    'updateCustomItem' : IDL.Func([CustomItemId, CustomItem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
