/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type CharacterId = bigint;
export interface Abilities {
    cha: bigint;
    con: bigint;
    dex: bigint;
    int: bigint;
    str: bigint;
    wis: bigint;
}
export interface Skills {
    perception: boolean;
    animalHandling: boolean;
    nature: boolean;
    investigation: boolean;
    deception: boolean;
    sleightOfHand: boolean;
    acrobatics: boolean;
    description: string;
    athletics: boolean;
    history: boolean;
    persuasion: boolean;
    medicine: boolean;
    stealth: boolean;
    survival: boolean;
    insight: boolean;
    intimidation: boolean;
    performance: boolean;
    arcana: boolean;
    religion: boolean;
}
export type TraitId = bigint;
export type RaceId = bigint;
export interface Spell {
    duration: string;
    school: string;
    name: string;
    damageEffect: string;
    components: string;
    description: string;
    level: bigint;
    characterId: CharacterId;
    range: string;
    castingTime: string;
}
export interface CustomClass {
    features: Array<Trait>;
    name: string;
    hitDie: bigint;
    description: string;
    proficiencies: Array<string>;
}
export type InventoryItemId = bigint;
export interface Character {
    ac: bigint;
    cha: bigint;
    con: bigint;
    dex: bigint;
    int: bigint;
    str: bigint;
    wis: bigint;
    spellSlots: Array<bigint>;
    characterClass: string;
    background: string;
    hpMax: bigint;
    owner: Principal;
    gold: bigint;
    name: string;
    race: string;
    hpCurrent: bigint;
    level: bigint;
    speed: bigint;
    gender: string;
    notes: string;
    skills: Skills;
    proficiencyBonus: bigint;
    alignment: string;
    initiative: bigint;
}
export interface Trait {
    source: string;
    name: string;
    description: string;
    characterId: CharacterId;
}
export interface InventoryItem {
    weight: bigint;
    name: string;
    description: string;
    equipped: boolean;
    quantity: bigint;
    characterId: CharacterId;
}
export interface Settings {
    maxLevel: bigint;
}
export interface CustomItem {
    weight: string;
    value: string;
    owner: Principal;
    name: string;
    description: string;
    itemType: string;
    rarity: string;
}
export type SpellId = bigint;
export interface CustomSpell {
    duration: string;
    owner: Principal;
    school: string;
    name: string;
    damageEffect: string;
    components: string;
    description: string;
    level: bigint;
    range: string;
    castingTime: string;
}
export type CustomAbilityId = bigint;
export type CharacterAbilityId = bigint;
export type CustomSpellId = bigint;
export interface CustomRace {
    abilityBonuses: Abilities;
    traits: Array<Trait>;
    name: string;
    description: string;
    speed: bigint;
}
export type CustomItemId = bigint;
export type ClassId = bigint;
export interface CustomAbility {
    owner: Principal;
    name: string;
    uses: bigint;
    description: string;
    abilityType: string;
    rechargeOn: string;
}
export interface UserProfile {
    name: string;
}
export interface CharacterAbility {
    usesRemaining: bigint;
    name: string;
    uses: bigint;
    description: string;
    abilityType: string;
    rechargeOn: string;
    characterId: CharacterId;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCharacterAbility(ability: CharacterAbility): Promise<CharacterAbilityId>;
    addClass(cls: CustomClass): Promise<ClassId>;
    addCustomAbility(ability: CustomAbility): Promise<CustomAbilityId>;
    addCustomItem(item: CustomItem): Promise<CustomItemId>;
    addCustomSpell(spell: CustomSpell): Promise<CustomSpellId>;
    addItem(item: InventoryItem): Promise<InventoryItemId>;
    addRace(race: CustomRace): Promise<RaceId>;
    addSpell(spell: Spell): Promise<SpellId>;
    addTrait(trait: Trait): Promise<TraitId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCharacter(char: Character): Promise<CharacterId>;
    deleteCharacter(id: CharacterId): Promise<void>;
    deleteCharacterAbility(id: CharacterAbilityId): Promise<void>;
    deleteClass(id: ClassId): Promise<void>;
    deleteCustomAbility(id: CustomAbilityId): Promise<void>;
    deleteCustomItem(id: CustomItemId): Promise<void>;
    deleteCustomSpell(id: CustomSpellId): Promise<void>;
    deleteItem(id: InventoryItemId): Promise<void>;
    deleteRace(id: RaceId): Promise<void>;
    deleteSpell(id: SpellId): Promise<void>;
    deleteTrait(id: TraitId): Promise<void>;
    getAbilitiesByCharacter(characterId: CharacterId): Promise<Array<[CharacterAbilityId, CharacterAbility]>>;
    getAllCharacters(): Promise<Array<[CharacterId, Character]>>;
    getAllCharactersCount(arg0: {
    }): Promise<bigint>;
    getAllClasses(): Promise<Array<[ClassId, CustomClass]>>;
    getAllCustomAbilities(): Promise<Array<[CustomAbilityId, CustomAbility]>>;
    getAllCustomItems(): Promise<Array<[CustomItemId, CustomItem]>>;
    getAllCustomSpells(): Promise<Array<[CustomSpellId, CustomSpell]>>;
    getAllRaces(): Promise<Array<[RaceId, CustomRace]>>;
    getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCharacter(id: CharacterId): Promise<Character | null>;
    getItemsByCharacter(characterId: CharacterId): Promise<Array<[InventoryItemId, InventoryItem]>>;
    getSettings(): Promise<Settings>;
    getSpellsByCharacter(characterId: CharacterId): Promise<Array<[SpellId, Spell]>>;
    getTraitsByCharacter(characterId: CharacterId): Promise<Array<[TraitId, Trait]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCharacter(id: CharacterId, char: Character): Promise<void>;
    updateCharacterAbility(id: CharacterAbilityId, ability: CharacterAbility): Promise<void>;
    updateClass(id: ClassId, cls: CustomClass): Promise<void>;
    updateCustomAbility(id: CustomAbilityId, ability: CustomAbility): Promise<void>;
    updateCustomItem(id: CustomItemId, item: CustomItem): Promise<void>;
    updateCustomSpell(id: CustomSpellId, spell: CustomSpell): Promise<void>;
    updateItem(id: InventoryItemId, item: InventoryItem): Promise<void>;
    updateRace(id: RaceId, race: CustomRace): Promise<void>;
    updateSettings(newSettings: Settings): Promise<void>;
    updateSpell(id: SpellId, spell: Spell): Promise<void>;
    updateTrait(id: TraitId, trait: Trait): Promise<void>;
}
import type { Character as _Character, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCharacterAbility(arg0: CharacterAbility): Promise<CharacterAbilityId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCharacterAbility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCharacterAbility(arg0);
            return result;
        }
    }
    async addClass(arg0: CustomClass): Promise<ClassId> {
        if (this.processError) {
            try {
                const result = await this.actor.addClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClass(arg0);
            return result;
        }
    }
    async addCustomAbility(arg0: CustomAbility): Promise<CustomAbilityId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomAbility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomAbility(arg0);
            return result;
        }
    }
    async addCustomItem(arg0: CustomItem): Promise<CustomItemId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomItem(arg0);
            return result;
        }
    }
    async addCustomSpell(arg0: CustomSpell): Promise<CustomSpellId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomSpell(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomSpell(arg0);
            return result;
        }
    }
    async addItem(arg0: InventoryItem): Promise<InventoryItemId> {
        if (this.processError) {
            try {
                const result = await this.actor.addItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItem(arg0);
            return result;
        }
    }
    async addRace(arg0: CustomRace): Promise<RaceId> {
        if (this.processError) {
            try {
                const result = await this.actor.addRace(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRace(arg0);
            return result;
        }
    }
    async addSpell(arg0: Spell): Promise<SpellId> {
        if (this.processError) {
            try {
                const result = await this.actor.addSpell(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSpell(arg0);
            return result;
        }
    }
    async addTrait(arg0: Trait): Promise<TraitId> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrait(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrait(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCharacter(arg0: Character): Promise<CharacterId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCharacter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCharacter(arg0);
            return result;
        }
    }
    async deleteCharacter(arg0: CharacterId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCharacter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCharacter(arg0);
            return result;
        }
    }
    async deleteCharacterAbility(arg0: CharacterAbilityId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCharacterAbility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCharacterAbility(arg0);
            return result;
        }
    }
    async deleteClass(arg0: ClassId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClass(arg0);
            return result;
        }
    }
    async deleteCustomAbility(arg0: CustomAbilityId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomAbility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomAbility(arg0);
            return result;
        }
    }
    async deleteCustomItem(arg0: CustomItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomItem(arg0);
            return result;
        }
    }
    async deleteCustomSpell(arg0: CustomSpellId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomSpell(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomSpell(arg0);
            return result;
        }
    }
    async deleteItem(arg0: InventoryItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItem(arg0);
            return result;
        }
    }
    async deleteRace(arg0: RaceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRace(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRace(arg0);
            return result;
        }
    }
    async deleteSpell(arg0: SpellId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSpell(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSpell(arg0);
            return result;
        }
    }
    async deleteTrait(arg0: TraitId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrait(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrait(arg0);
            return result;
        }
    }
    async getAbilitiesByCharacter(arg0: CharacterId): Promise<Array<[CharacterAbilityId, CharacterAbility]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAbilitiesByCharacter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAbilitiesByCharacter(arg0);
            return result;
        }
    }
    async getAllCharacters(): Promise<Array<[CharacterId, Character]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCharacters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCharacters();
            return result;
        }
    }
    async getAllCharactersCount(arg0: {
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCharactersCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCharactersCount(arg0);
            return result;
        }
    }
    async getAllClasses(): Promise<Array<[ClassId, CustomClass]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClasses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClasses();
            return result;
        }
    }
    async getAllCustomAbilities(): Promise<Array<[CustomAbilityId, CustomAbility]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomAbilities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomAbilities();
            return result;
        }
    }
    async getAllCustomItems(): Promise<Array<[CustomItemId, CustomItem]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomItems();
            return result;
        }
    }
    async getAllCustomSpells(): Promise<Array<[CustomSpellId, CustomSpell]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomSpells();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomSpells();
            return result;
        }
    }
    async getAllRaces(): Promise<Array<[RaceId, CustomRace]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRaces();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRaces();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCharacter(arg0: CharacterId): Promise<Character | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCharacter(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCharacter(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItemsByCharacter(arg0: CharacterId): Promise<Array<[InventoryItemId, InventoryItem]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemsByCharacter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemsByCharacter(arg0);
            return result;
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getSpellsByCharacter(arg0: CharacterId): Promise<Array<[SpellId, Spell]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpellsByCharacter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpellsByCharacter(arg0);
            return result;
        }
    }
    async getTraitsByCharacter(arg0: CharacterId): Promise<Array<[TraitId, Trait]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTraitsByCharacter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTraitsByCharacter(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCharacter(arg0: CharacterId, arg1: Character): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCharacter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCharacter(arg0, arg1);
            return result;
        }
    }
    async updateCharacterAbility(arg0: CharacterAbilityId, arg1: CharacterAbility): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCharacterAbility(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCharacterAbility(arg0, arg1);
            return result;
        }
    }
    async updateClass(arg0: ClassId, arg1: CustomClass): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClass(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClass(arg0, arg1);
            return result;
        }
    }
    async updateCustomAbility(arg0: CustomAbilityId, arg1: CustomAbility): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomAbility(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomAbility(arg0, arg1);
            return result;
        }
    }
    async updateCustomItem(arg0: CustomItemId, arg1: CustomItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomItem(arg0, arg1);
            return result;
        }
    }
    async updateCustomSpell(arg0: CustomSpellId, arg1: CustomSpell): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomSpell(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomSpell(arg0, arg1);
            return result;
        }
    }
    async updateItem(arg0: InventoryItemId, arg1: InventoryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItem(arg0, arg1);
            return result;
        }
    }
    async updateRace(arg0: RaceId, arg1: CustomRace): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRace(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRace(arg0, arg1);
            return result;
        }
    }
    async updateSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
    async updateSpell(arg0: SpellId, arg1: Spell): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSpell(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSpell(arg0, arg1);
            return result;
        }
    }
    async updateTrait(arg0: TraitId, arg1: Trait): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrait(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrait(arg0, arg1);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Character]): Character | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
